### PR TITLE
fixed issue where boards were overlapping each other

### PR DESCRIPTION
**Pull request by sej7278**
Seems boardWidth was being used everywhere whereas for Y-axis you should be using boardHeight to cope with non-square boards.

added some comments to highlight which Edge.Cut was being rendered.

added shebang so you could just run ./panelizer.py 4 4

made NUM_X and NUM_Y arguments too

added -v / --verbose option to show/hide the progressbar

### CODE REVIEW

**Comment by willemcvu** [comment]
Hiya - super awesome to see improvements to this script.
Mind submitting another pull request with the improvements you made in the past couple days? Thanks!

**Comment by sej7278** [comment]
hi, i've removed the progressbar so not sure you'll want a PR now? the verbose argument i made in the PR was becoming too much code and the script works so fast the progressbar seemed pointless.

you're welcome to manually merge in my changes around shebang/non-square/arguments of course:

https://github.com/sej7278/kicad-panelizer/commit/b7c84426f539d2aa2ae61bc5df441854ecb5d69f

or i can do a new PR if you really want?

**Comment by willemcvu** [comment]
The progress bar is left over from a hackish way of determining zone nets
that I copied from someone else's script, and it took a while to run. Since
it runs so fast now the progress bar is 100% useless.
I'm manually merge in your changes, since that's OK w/ you.

**Comment by willemcvu** [comment]
Whoops, just saw you put in a new PR. I went ahead and merged it, thanks!

**Comment by sej7278** [comment]
cool, yeah i had a brainfart and git reset my new branch locally, then managed to get it back from github.

in my master i've removed the progressbar and some print statements (so removed my verbose argument again) and added hrail and vrail arguments

**Pull request closed without merging**
